"""
FloatChat - Optional LLM Layer
=================================
Everything in FloatChat works with ZERO API keys using the rule-based
nlp_engine + template summaries below (important for a hackathon demo
with unreliable venue WiFi). If ANTHROPIC_API_KEY is set, this module
upgrades the chat responses to be generated by Claude for a more
natural, context-aware conversational feel, and can help disambiguate
queries the rule-based parser flags as low-confidence.

This is intentionally a thin, isolated layer: the LLM is NEVER given
write access to the database and NEVER asked to invent numbers -- it
only receives already-retrieved, grounded summary statistics and is
asked to phrase them naturally. This "retrieve first, generate second"
order is what avoids the hallucination failure mode flagged in the PS
analysis ("LLM answers from its own knowledge instead of querying the
database" was listed as a red flag evaluators watch for).
"""

import os

try:
    import anthropic
    _HAS_SDK = True
except ImportError:
    _HAS_SDK = False


def llm_available():
    return _HAS_SDK and bool(os.environ.get("ANTHROPIC_API_KEY"))


def summarize_with_llm(user_query: str, filter_description: str, stats: dict) -> str:
    """
    Ask Claude to phrase a natural-language summary of ALREADY-COMPUTED
    stats. The model is not permitted to add new facts.
    """
    if not llm_available():
        return None

    client = anthropic.Anthropic()
    prompt = f"""You are FloatChat, an oceanographic data assistant. A user asked:
"{user_query}"

The system retrieved this data (already computed from a real database, do not invent
any other numbers, floats, or values beyond what is given):

Filter applied: {filter_description}
Stats: {stats}

Write a concise (2-4 sentence) natural-language answer for the user, referencing the
concrete numbers given. End with one short follow-up suggestion (e.g. a related
question they could ask next). Do not mention that you are an AI or that this is
computed data -- just answer like a helpful oceanographer would."""

    try:
        resp = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=300,
            messages=[{"role": "user", "content": prompt}],
        )
        return "".join(b.text for b in resp.content if hasattr(b, "text"))
    except Exception as e:
        return None


def template_summary(user_query: str, filter_description: str, stats: dict) -> str:
    """Offline fallback: deterministic, still informative summary."""
    if not stats or stats.get("n_profiles", 0) == 0:
        return (f"I couldn't find any matching profiles for *{filter_description}*. "
                f"Try widening the date range, or ask about one of the available regions "
                f"(Arabian Sea, Bay of Bengal, Equatorial Indian Ocean, Andaman Sea, "
                f"Southern Indian Ocean).")

    lines = [f"Found **{stats['n_profiles']} profiles** from **{stats.get('n_floats', '?')} floats** "
             f"matching {filter_description}."]
    if "mean_value" in stats and stats["mean_value"] is not None:
        lines.append(f"Mean {stats.get('var_label', 'value')}: **{stats['mean_value']:.2f}** "
                      f"(range {stats.get('min_value', 0):.2f} – {stats.get('max_value', 0):.2f}).")
    if stats.get("date_range"):
        lines.append(f"Date range in results: {stats['date_range'][0]} → {stats['date_range'][1]}.")
    if stats.get("delayed_pct") is not None:
        lines.append(f"{stats['delayed_pct']:.0f}% of profiles are delayed-mode (QC-adjusted); "
                      f"the rest are real-time.")
    return " ".join(lines)
